version: '3.1'

services:

  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    network_mode: host


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080